// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	getSettings: () => typedError<Settings, AppError>(__TAURI_INVOKE("get_settings")),
	/**  Saves the full settings object and returns what was stored. */
	updateSettings: (settings: Settings) => typedError<Settings, AppError>(__TAURI_INVOKE("update_settings", { settings })),
	getSidebar: () => typedError<Sidebar, AppError>(__TAURI_INVOKE("get_sidebar")),
	/**  One page of the list. Pass the previous page's `next` as `after` to continue. */
	listArticles: (query: ArticleQuery, after: {
	publishedAt: number,
	id: number,
} | null, limit: number) => typedError<ArticlePage, AppError>(__TAURI_INVOKE("list_articles", { query, after, limit })),
	getArticle: (id: number) => typedError<Article, AppError>(__TAURI_INVOKE("get_article", { id })),
	/**  Marks articles read or unread; returns how many changed. */
	setArticlesRead: (ids: number[], read: boolean) => typedError<number, AppError>(__TAURI_INVOKE("set_articles_read", { ids, read })),
	setArticleStarred: (id: number, starred: boolean) => typedError<null, AppError>(__TAURI_INVOKE("set_article_starred", { id, starred })),
	/**  Finds the feeds behind a feed or website address. */
	discoverFeeds: (url: string) => typedError<DiscoveredFeed[], AppError>(__TAURI_INVOKE("discover_feeds", { url })),
	previewFeed: (url: string) => typedError<FeedPreview, AppError>(__TAURI_INVOKE("preview_feed", { url })),
	/**  Subscribes and returns the new feed's id. */
	subscribeFeed: (request: SubscribeRequest) => typedError<number, AppError>(__TAURI_INVOKE("subscribe_feed", { request })),
	getFeed: (id: number) => typedError<FeedDetails, AppError>(__TAURI_INVOKE("get_feed", { id })),
	updateFeed: (id: number, update: FeedUpdate) => typedError<FeedDetails, AppError>(__TAURI_INVOKE("update_feed", { id, update })),
	/**  Unsubscribes; starred articles are kept under "Deleted feeds". */
	unsubscribeFeed: (id: number) => typedError<null, AppError>(__TAURI_INVOKE("unsubscribe_feed", { id })),
	createFolder: (name: string) => typedError<number, AppError>(__TAURI_INVOKE("create_folder", { name })),
	renameFolder: (id: number, name: string) => typedError<null, AppError>(__TAURI_INVOKE("rename_folder", { id, name })),
	/**  Deletes a folder; its feeds move to the top level. */
	deleteFolder: (id: number) => typedError<null, AppError>(__TAURI_INVOKE("delete_folder", { id })),
	/**  Saves the sidebar order after a drag and drop. */
	reorderSidebar: (order: SidebarOrder) => typedError<null, AppError>(__TAURI_INVOKE("reorder_sidebar", { order })),
	refresh: (target: RefreshTarget) => typedError<null, AppError>(__TAURI_INVOKE("refresh", { target })),
	getRefreshStatus: () => typedError<RefreshStatus, AppError>(__TAURI_INVOKE("get_refresh_status")),
	/**  Opens a link in the OS default browser or mail client (SPEC §6.2, §8.2). */
	openExternal: (url: string) => typedError<null, AppError>(__TAURI_INVOKE("open_external", { url })),
};

/** Events */
export const events = {
	articlesChanged: makeEvent<ArticlesChanged>("articles:changed"),
	feedError: makeEvent<FeedError>("feed:error"),
	refreshDone: makeEvent<RefreshDone>("refresh:done"),
	refreshProgress: makeEvent<RefreshProgress>("refresh:progress"),
};

/* Types */
/**
 *  The error type returned by every public backend function (SPEC §4.1).
 * 
 *  Serialises to the frontend as `{ kind, message }`, where `message` is readable by users.
 */
export type AppError = {
	kind: ErrorKind,
	message: string,
};

export type Article = {
	id: number,
	feedId: number,
	feedTitle: string,
	title: string,
	url: string | null,
	author: string | null,
	/**  Sanitised HTML. */
	contentHtml: string,
	publishedAt: number | null,
	isRead: boolean,
	isStarred: boolean,
	enclosures: Enclosure[],
};

/**  Position in an article list; pass back to get the next page (keyset pagination). */
export type ArticleCursor = {
	publishedAt: number,
	id: number,
};

export type ArticleListItem = {
	id: number,
	feedId: number,
	feedTitle: string,
	title: string,
	/**  Plain-text excerpt, at most ~140 characters. */
	summary: string,
	publishedAt: number | null,
	isRead: boolean,
	isStarred: boolean,
};

export type ArticlePage = {
	items: ArticleListItem[],
	/**  `None` when this is the last page. */
	next: ArticleCursor | null,
};

export type ArticleQuery = {
	view: View,
	unreadOnly: boolean,
	sort: SortOrder,
};

/**  Articles were added or changed outside a user action (refresh, subscribe). */
export type ArticlesChanged = {
	newCount: number,
};

/**  A feed found by discovery (SPEC §6.1). */
export type DiscoveredFeed = {
	url: string,
	title: string | null,
};

export type Enclosure = {
	url: string,
	mimeType: string | null,
	length: number | null,
};

/**  Broad category of an [`AppError`], so the frontend can react without parsing messages. */
export type ErrorKind = "database" | "io" | "network" | 
/**  The document isn't a feed we can read. */
"invalid_feed" | "not_found" | "invalid_input" | 
/**  Would create a duplicate, e.g. subscribing to a feed twice. */
"conflict" | "internal";

/**  Everything the "Edit feed" dialog shows. */
export type FeedDetails = {
	id: number,
	url: string,
	/**  The title the feed itself provides. */
	title: string,
	customTitle: string | null,
	siteUrl: string | null,
	folderId: number | null,
	/**
	 *  Refresh interval override in seconds; `None` uses the global setting, `0` means
	 *  manual refresh only.
	 */
	fetchInterval: number | null,
	paused: boolean,
	errorCount: number,
	lastError: string | null,
	lastFetchedAt: number | null,
};

export type FeedError = {
	feedId: number,
	message: string,
};

export type FeedNode = {
	id: number,
	folderId: number | null,
	/**  Custom title if set, else the feed's own title. */
	title: string,
	siteUrl: string | null,
	unreadCount: number,
	errorCount: number,
	lastError: string | null,
	/**  File name of the cached favicon (served as `omarss-img://…/icon/<name>`). */
	icon: string | null,
	paused: boolean,
};

export type FeedPlacement = {
	id: number,
	folderId: number | null,
};

/**  What a feed looks like before subscribing (SPEC §6.1: title and the last 5 items). */
export type FeedPreview = {
	url: string,
	title: string,
	siteUrl: string | null,
	items: PreviewItem[],
};

export type FeedUpdate = {
	/**  Empty or `None` clears the custom title. */
	customTitle: string | null,
	folderId: number | null,
	/**  See [`FeedDetails::fetch_interval`]. */
	fetchInterval: number | null,
	paused: boolean,
};

export type FolderNode = {
	id: number,
	name: string,
	unreadCount: number,
	feeds: FeedNode[],
};

export type PreviewItem = {
	title: string,
	url: string | null,
	publishedAt: number | null,
};

export type RefreshDone = {
	newCount: number,
	errors: number,
	/**  Every feed failed to connect, so automatic refresh waits for the network. */
	offline: boolean,
};

export type RefreshProgress = {
	done: number,
	total: number,
};

export type RefreshStatus = {
	running: boolean,
	done: number,
	total: number,
	/**
	 *  Every feed failed to connect in the last run, so automatic refresh is waiting for the
	 *  network to come back (SPEC §7.2).
	 */
	offline: boolean,
	lastFinishedAt: number | null,
};

export type RefreshTarget = { kind: "all" } | { kind: "feed"; id: number } | { kind: "folder"; id: number };

export type Settings = {
	theme: Theme,
	/**  Global refresh interval in minutes; `0` means manual refresh only (SPEC §6.5). */
	refreshIntervalMinutes: number,
	refreshOnStartup: boolean,
	/**  Mark an article unread again when its feed updates it (SPEC §7.4). */
	markUpdatedUnread: boolean,
};

export type Sidebar = {
	counts: ViewCounts,
	folders: FolderNode[],
	/**  Feeds that are not in any folder. */
	feeds: FeedNode[],
	/**  Starred articles kept from unsubscribed feeds, if there are any. */
	deletedFeeds: FeedNode | null,
};

/**
 *  The full sidebar order after a drag and drop: folders top to bottom, then every feed top
 *  to bottom with the folder it now belongs to.
 */
export type SidebarOrder = {
	folders: number[],
	feeds: FeedPlacement[],
};

export type SortOrder = "newestFirst" | "oldestFirst";

export type SubscribeRequest = {
	url: string,
	folderId: number | null,
	/**  Optional custom title. */
	title: string | null,
};

export type Theme = "light" | "dark" | "system";

/**  Which set of articles the list shows. */
export type View = { kind: "all" } | { kind: "unread" } | { kind: "starred" } | { kind: "today" } | { kind: "feed"; id: number } | { kind: "folder"; id: number };

export type ViewCounts = {
	unread: number,
	starred: number,
	/**  Unread articles published since local midnight. */
	today: number,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

