// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	getSettings: () => typedError<Settings, AppError>(__TAURI_INVOKE("get_settings")),
	/**  Saves the full settings object and returns what was stored. */
	updateSettings: (settings: Settings) => typedError<Settings, AppError>(__TAURI_INVOKE("update_settings", { settings })),
	getSidebar: () => typedError<Sidebar, AppError>(__TAURI_INVOKE("get_sidebar")),
	listArticles: (query: ArticleQuery) => typedError<ArticleListItem[], AppError>(__TAURI_INVOKE("list_articles", { query })),
	getArticle: (id: number) => typedError<Article, AppError>(__TAURI_INVOKE("get_article", { id })),
	/**  Opens a link in the OS default browser or mail client (SPEC §6.2, §8.2). */
	openExternal: (url: string) => typedError<null, AppError>(__TAURI_INVOKE("open_external", { url })),
};

/* Types */
/**
 *  The error type returned by every public backend function (SPEC §4.1).
 * 
 *  Serialises to the frontend as `{ kind, message }`, where `message` is readable by users.
 */
export type AppError = {
	kind: ErrorKind,
	message: string,
};

export type Article = {
	id: number,
	feedId: number,
	feedTitle: string,
	title: string,
	url: string | null,
	author: string | null,
	/**  Sanitised HTML. */
	contentHtml: string,
	publishedAt: number | null,
	isRead: boolean,
	isStarred: boolean,
	enclosures: Enclosure[],
};

export type ArticleListItem = {
	id: number,
	feedId: number,
	feedTitle: string,
	title: string,
	/**  Plain-text excerpt, at most ~140 characters. */
	summary: string,
	publishedAt: number | null,
	isRead: boolean,
	isStarred: boolean,
};

export type ArticleQuery = {
	view: View,
	unreadOnly: boolean,
	sort: SortOrder,
};

export type Enclosure = {
	url: string,
	mimeType: string | null,
	length: number | null,
};

/**  Broad category of an [`AppError`], so the frontend can react without parsing messages. */
export type ErrorKind = "database" | "io" | "not_found" | "invalid_input" | "internal";

export type FeedNode = {
	id: number,
	folderId: number | null,
	title: string,
	siteUrl: string | null,
	unreadCount: number,
	errorCount: number,
};

export type FolderNode = {
	id: number,
	name: string,
	unreadCount: number,
	feeds: FeedNode[],
};

export type Settings = {
	theme: Theme,
};

export type Sidebar = {
	counts: ViewCounts,
	folders: FolderNode[],
	/**  Feeds that are not in any folder. */
	feeds: FeedNode[],
};

export type SortOrder = "newestFirst" | "oldestFirst";

export type Theme = "light" | "dark" | "system";

/**  Which set of articles the list shows. */
export type View = { kind: "all" } | { kind: "unread" } | { kind: "starred" } | { kind: "today" } | { kind: "feed"; id: number } | { kind: "folder"; id: number };

export type ViewCounts = {
	unread: number,
	starred: number,
	/**  Unread articles published since local midnight. */
	today: number,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

